<?php

// $Header: /cvsroot/bitweaver/_bit_calendar/index.php,v 1.1 2005/07/15 12:25:01 bitweaver Exp $

// Copyright (c) 2002-2003, Luis Argerich, Garland Foster, Eduardo Polidor, et. al.
// All Rights Reserved. See copyright.txt for details and a complete list of authors.
// Licensed under the GNU LESSER GENERAL PUBLIC LICENSE. See license.txt for details.
require_once( '../bit_setup_inc.php' );

include_once( CALENDAR_PKG_PATH.'calendar_lib.php' );

# perms are 
# 	$bit_p_view_calendar
# 	$bit_p_admin_calendar
# 	$bit_p_change_events
# 	$bit_p_add_events
$gBitSystem->isPackageActive('calendar', TRUE);

$bufid = array();
$bufdata = array();
$modifiable = array();

$calendarlib = new CalendarLib();
$calendarlib->loadContentTypes();		

$rawcals = $calendarlib->listCalendars();

foreach ($rawcals["data"] as $cal_id=>$cal_data) {
	if ($bit_p_admin == 'y') {
		$cal_data["bit_p_view_calendar"] = 'y';
		$cal_data["bit_p_add_events"] = 'y';
		$cal_data["bit_p_change_events"] = 'y';
	} else {
			$cal_data["bit_p_view_calendar"] = 'y';
			$cal_data["bit_p_add_events"] = 'y';
			$cal_data["bit_p_change_events"] = 'y';
	}
	if ($cal_data["bit_p_view_calendar"] == 'y') {
		$bufid[] = $cal_id;
		$bufdata["$cal_id"] = $cal_data;
	}
	if (($cal_data["bit_p_add_events"] == 'y') or ($cal_data["bit_p_change_events"] == 'y')) {
		$modifiable[] = $cal_id;
	}
}
$listcals = $bufid;
$infocals["data"] = $bufdata;

$smarty->assign('infocals', $infocals["data"]);
$smarty->assign('listcals', $listcals);
$smarty->assign('modifiable', count($modifiable));

// set up list of groups 
if (isset($_REQUEST["calIds"])and is_array($_REQUEST["calIds"])and count($_REQUEST["calIds"])) {
	$_SESSION['CalendarViewGroups'] = $_REQUEST["calIds"];
} elseif (!isset($_SESSION['CalendarViewGroups'])) {
	$_SESSION['CalendarViewGroups'] = $listcals;
} elseif (isset($_REQUEST["refresh"])and !isset($_REQUEST["calIds"])) {
	$_SESSION['CalendarViewGroups'] = array();
}

// setup list of tiki items displayed
if (isset($_REQUEST["tikicals"])and is_array($_REQUEST["tikicals"])and count($_REQUEST["tikicals"])) {
	$_SESSION['CalendarViewTikiCals'] = $_REQUEST["tikicals"];
} elseif (!isset($_SESSION['CalendarViewTikiCals'])) {
	$_SESSION['CalendarViewTikiCals'] = array();
} elseif (isset($_REQUEST["refresh"])and !isset($_REQUEST["tikicals"])) {
	$_SESSION['CalendarViewTikiCals'] = array();
}

// this should be a global array generated by the some object in the kernel
$tikiItems = $calendarlib->gContentTypes;
$smarty->assign('tikiItems', $tikiItems);

$smarty->assign('displayedcals', $_SESSION['CalendarViewGroups']);
$smarty->assign('displayedtikicals', $_SESSION['CalendarViewTikiCals']);

$thiscal = array();

foreach ($listcals as $thatid) {
	if (is_array($_SESSION['CalendarViewGroups']) && (in_array("$thatid", $_SESSION['CalendarViewGroups']))) {
		$thiscal["$thatid"] = 1;
	} else {
		$thiscal["$thatid"] = 0;
	}
}

$smarty->assign('thiscal', $thiscal);

$tikical = array();

foreach ($_SESSION['CalendarViewTikiCals'] as $calt) {
	$tikical["$calt"] = 1;
}

$trunc = "12"; // put in a pref, number of chars displayed in cal cells
$smarty->assign('tikical', $tikical);

if (isset($_REQUEST["todate"]) && $_REQUEST['todate']) {
	$_SESSION['CalendarFocusDate'] = $_REQUEST['todate'];
} elseif (isset($_SESSION['CalendarFocusDate']) && $_SESSION['CalendarFocusDate']) {
	$_REQUEST["todate"] = $_SESSION['CalendarFocusDate'];
} else {
	$_SESSION['CalendarFocusDate'] = mktime(0, 0, 0, date('m'), date('d'), date('Y'));
	$_REQUEST["todate"] = $_SESSION['CalendarFocusDate'];
}

$focusdate = $_REQUEST['todate'];
list($focus_day, $focus_month, $focus_year) = array(
	date("d", $focusdate),
	date("m", $focusdate),
	date("Y", $focusdate)
);
$focusdate = mktime(0,0,0,$focus_month,$focus_day,$focus_year);

if (isset($_REQUEST["viewmode"]) and $_REQUEST["viewmode"]) {
	$_SESSION['CalendarViewMode'] = $_REQUEST["viewmode"];
}

if (!isset($_SESSION['CalendarViewMode']) or !$_SESSION['CalendarViewMode']) {
	$_SESSION['CalendarViewMode'] = 'month';
}
$smarty->assign('viewmode', $_SESSION['CalendarViewMode']);

if (isset($_REQUEST["delete"])and ($_REQUEST["delete"]) and isset($_REQUEST["calitem_id"])) {
	$calendarlib->dropItem($user_id, $_REQUEST["calitem_id"]);
	$_REQUEST["calitem_id"] = 0;
}

if (!isset($_REQUEST["calitem_id"]))
	$_REQUEST["calitem_id"] = 0;

if (!isset($_REQUEST["location_id"]))
	$_REQUEST["location_id"] = 0;

if (!isset($_REQUEST["category_id"]))
	$_REQUEST["category_id"] = 0;

if (!isset($_REQUEST["organizers"]))
	$_REQUEST["organizers"] = "";

if (!isset($_REQUEST["participants"]))
	$_REQUEST["participants"] = "";

if (!isset($_REQUEST["newloc"]))
	$_REQUEST["newloc"] = "";

if (!isset($_REQUEST["newcat"]))
	$_REQUEST["newcat"] = "";

if (!isset($_REQUEST["priority"]))
	$_REQUEST["priority"] = "5";

if (!isset($_REQUEST["lang"]))
	$_REQUEST["lang"] = $gBitLanguage;

if (!isset($_REQUEST["status"]))
	$_REQUEST["status"] = 0;

if (isset($_REQUEST["copy"])and ($_REQUEST["copy"])) {
	
	$_REQUEST["calitem_id"] = 0;
	$_REQUEST["save"] = true;
}

if (isset($_REQUEST["save"])and ($_REQUEST["save"])) {
	
	if (!isset($_REQUEST["name"])or !(trim($_REQUEST["name"]))) {
		$_REQUEST["name"] = tra("event without name");
	}
	if (isset($_REQUEST["start_date_input"]) and $_REQUEST["start_date_input"]) {
		$event_start = strtotime($_REQUEST["start_date_input"]);
	} else {
		if (isset($_REQUEST["start_freeform"])and $_REQUEST["start_freeform"]) {
			$event_start = strtotime($_REQUEST["start_freeform"]);
		}
		if (!isset($event_start)) {
			$event_start = mktime($_REQUEST["starth_Hour"], $_REQUEST["starth_Minute"],
					0, $_REQUEST["start_Month"], $_REQUEST["start_Day"], $_REQUEST["start_Year"]);
		}
	}
	if (isset($_REQUEST["end_date_input"]) and $_REQUEST["end_date_input"]) {
		$event_end = strtotime($_REQUEST["end_date_input"]);
	} else {
		if (isset($_REQUEST["end_freeform"])and $_REQUEST["end_freeform"]) {
			$event_end = strtotime($_REQUEST["end_freeform"]);
		}
		if (!isset($event_end)) {
			$event_end = mktime($_REQUEST["endh_Hour"], $_REQUEST["endh_Minute"],
					0, $_REQUEST["end_Month"], $_REQUEST["end_Day"], $_REQUEST["end_Year"]);
		}
	}
	$_REQUEST["calitem_id"] = $calendarlib->setItem($gBitUser->mUserId, $_REQUEST["calitem_id"], array(
		"user_id" => $gBitUser->mUserId,
		"organizers" => $_REQUEST["organizers"],
		"participants" => $_REQUEST["participants"],
		"calendar_id" => $_REQUEST["calendar_id"],
		"start" => $event_start,
		"end" => $event_end,
		"location_id" => $_REQUEST["location_id"],
		"newloc" => $_REQUEST["newloc"],
		"category_id" => $_REQUEST["category_id"],
		"newcat" => $_REQUEST["newcat"],
		"priority" => $_REQUEST["priority"],
		"status" => $_REQUEST["status"],
		"url" => $_REQUEST["url"],
		"lang" => $_REQUEST["lang"],
		"name" => $_REQUEST["name"],
		"description" => $_REQUEST["description"]
	));
}

if ($_REQUEST["calitem_id"]) {
	$info = $calendarlib->getItem($_REQUEST["calitem_id"]);
} else {
	$info = array();

	$info["calitem_id"] = "";
	$info["calendar_id"] = "";
	$info["user_id"] = "";
	$info["calname"] = "";
	$info["organizers"] = $gBitUser->mUsername . ",";
	$info["participants"] = $gBitUser->mUsername . ":0,";
	$info["start_time"] = $focusdate + date("H") * 60 * 60;
	$info["end_time"] = $focusdate + (date("H") + 2) * 60 * 60;
	$info["location_id"] = 0;
	$info["locationName"] = '';
	$info["category_id"] = 0;
	$info["categoryName"] = '';
	$info["priority"] = 5;
	$info["url"] = '';
//	$info["lang"] = $gBitUser->getPreference("language");
	$info["name"] = '';
	$info["description"] = '';
	$info["created"] = time();
	$info["last_modified"] = time();
	$info["status"] = '0';
	$info["customlocations"] = 'n';
	$info["customcategories"] = 'n';
	$info["customlanguages"] = 'n';
	$info["custompriorities"] = 'n';
	$info["customparticipants"] = 'n';
}

if (!isset($_REQUEST["calendar_id"])or !$_REQUEST["calendar_id"]) {
	$_REQUEST["calendar_id"] = $info["calendar_id"];
}

$smarty->assign('calitem_id', $info["calitem_id"]);
$smarty->assign('calendar_id', $_REQUEST["calendar_id"]);
$smarty->assign('organizers', $info["organizers"]);
$smarty->assign('participants', $info["participants"]);
$smarty->assign('calname', $info["calname"]);
if (isset( $info["start_time"] ) ) {
  $smarty->assign('start_time', $info["start_time"]);
  $smarty->assign('end_time', $info["end_time"]);
}
$smarty->assign('location_id', $info["location_id"]);
//$smarty->assign('locationName', $info["locationName"]);
$smarty->assign('category_id', $info["category_id"]);
//$smarty->assign('categoryName', $info["categoryName"]);
$smarty->assign('priority', $info["priority"]);
$smarty->assign('url', $info["url"]);
//$smarty->assign('lang', $info["lang"]);
$smarty->assign('name', $info["name"]);
$smarty->assign('description', $info["description"]);
$smarty->assign('created', $info["created"]);
$smarty->assign('last_modified', $info["last_modified"]);
$smarty->assign('lastUser', $info["user_id"]);
$smarty->assign('status', $info["status"]);

if (!isset($_REQUEST["editmode"])) $_REQUEST["editmode"] = 0;

if ($_REQUEST["editmode"]) {
	$thatcal = $calendarlib->getCalendar($_REQUEST["calendar_id"]);

	$info["customlocations"] = $thatcal["customlocations"];
	$info["customcategories"] = $thatcal["customcategories"];
	$info["customlanguages"] = $thatcal["customlanguages"];
	$info["custompriorities"] = $thatcal["custompriorities"];
	$info["customparticipants"] = $thatcal["customparticipants"];
	$listcat = array();
	$listloc = array();
	$listpeople = array();
	$languages = array();

	if ($thatcal["customcategories"] == 'y') {
		$listcat = $calendarlib->listCategories($_REQUEST["calendar_id"]);
	}

	if ($thatcal["customlocations"] == 'y') {
		$listloc = $calendarlib->listLocations($_REQUEST["calendar_id"]);
	}

	if ($thatcal["customlanguages"] == 'y') {
		$languages = $tikilib->list_languages();
	}

	$smarty->assign('listcat', $listcat);
	$smarty->assign('listloc', $listloc);
	$smarty->assign_by_ref('languages', $languages);
}

$smarty->assign('customlocations', $info["customlocations"]);
$smarty->assign('customcategories', $info["customcategories"]);
$smarty->assign('customlanguages', $info["customlanguages"]);
$smarty->assign('custompriorities', $info["custompriorities"]);
$smarty->assign('customparticipants', $info["customparticipants"]);

if (isset($_REQUEST["find"])) {
	$find = $_REQUEST["find"];
} else {
	$find = '';
}

$smarty->assign('find', $find);

if (isset($_REQUEST['drop'])) {
	
	if (is_array($_REQUEST['drop'])) {
		foreach ($_REQUEST['drop'] as $dropme) {
			$calendarlib->dropItem($gBitUser->mUserId, $dropme);
		}
	} else {
		$calendarlib->dropItem($gBitUser->mUserId, $_REQUEST['drop']);
	}
}

$z = date("z");

$focus_prevday = mktime(0, 0, 0, $focus_month, $focus_day - 1, $focus_year);
$focus_nextday = mktime(0, 0, 0, $focus_month, $focus_day + 1, $focus_year);
$focus_prevweek = mktime(0, 0, 0, $focus_month, $focus_day - 7, $focus_year);
$focus_nextweek = mktime(0, 0, 0, $focus_month, $focus_day + 7, $focus_year);
$focus_prevmonth = mktime(0, 0, 0, $focus_month - 1, $focus_day, $focus_year);
$focus_nextmonth = mktime(0, 0, 0, $focus_month + 1, $focus_day, $focus_year);

$smarty->assign('daybefore', $focus_prevday);
$smarty->assign('weekbefore', $focus_prevweek);
$smarty->assign('monthbefore', $focus_prevmonth);
$smarty->assign('dayafter', $focus_nextday);
$smarty->assign('weekafter', $focus_nextweek);
$smarty->assign('monthafter', $focus_nextmonth);
$smarty->assign('focusmonth', $focus_month);
$smarty->assign('focusdate', $focusdate);
$smarty->assign('now', mktime(0, 0, 0, date('m'), date('d'), date('Y')));

$weekdays = range(0, 6);

$d = 60 * 60 * 24;
$currentweek = date("W", $focusdate);
$wd = date('w', $focusdate);

#if ($wd == 0) $w = 7;
#$wd--;

// calculate timespan for sql query
if ($_SESSION['CalendarViewMode'] == 'month') {
   $viewstart = mktime(0,0,0,$focus_month, 1, $focus_year);
   $TmpWeekday = date("w",$viewstart);
   // move viewstart back to Sunday....
   $viewstart -= $TmpWeekday * $d;
   // this is the last day of $focus_month
   $viewend = mktime(0,0,0,$focus_month + 1, 0, $focus_year);
   $TmpWeekday = date("w", $viewend);
   $viewend += (6 - $TmpWeekday) * $d;
   $viewend -= 1;
   // ISO weeks --- kinda mangled because ours begin on Sunday...
   $firstweek = date("W", $viewstart + $d);
   $lastweek = date("W", $viewend);
   if ($lastweek < $firstweek) {
	   if ($currentweek < $firstweek) {
		   $firstweek -= 52;
	   } else {
		   $lastweek += 52;
	   }
   }
   $numberofweeks = $lastweek - $firstweek;
} elseif ($_SESSION['CalendarViewMode'] == 'week') {
   $firstweek = $currentweek;
   $lastweek = $currentweek;
   // start by putting $viewstart at midnight starting focusdate
   $viewstart = mktime(0,0,0,$focus_month, $focus_day, $focus_year);
   // then back up to the preceding Sunday;
   $viewstart -= $wd * $d;
   // then go to the end of the week for $viewend
   $viewend = $viewstart + ((7 * $d) - 1);
   $numberofweeks = 0;
} else {
   $firstweek = $currentweek;
   $lastweek = $currentweek;
   $viewstart = mktime(0,0,0,$focus_month, $focus_day, $focus_year);
   $viewend = $viewstart + ($d - 1);
   $weekdays = array(date('w',$focusdate));
   $numberofweeks = 0;
}
// untested (by me, anyway!) function grabbed from the php.net site:
// [2004/01/05:rpg]
function m_weeks($y, $m){
  // monthday array
  $monthdays = array(1=>31, 3=>31, 4=>30, 5=>31, 6=>30,7=>31,
               8=>31, 9=>30, 10=>31, 11=>30, 12=>31);
  // weekdays remaining in a week starting on 7 - Sunday...(could be changed)
  $weekdays = array(7=>7, 1=>6, 2=>5, 3=>4, 4=>3, 5=>2, 6=>1);
  $date = mktime( 0, 0, 0, $m, 1, $y);
  $leap = date("L", $date);
  // if it is a leap year set February to 29 days, otherwise 28
  $monthdays[2] = ($leap ? 29 : 28);
  // get the weekday of the first day of the month
  $wn = strftime("%u",$date);
  $days = $monthdays[$m] - $weekdays[$wn];
  return (ceil($days/7) + 1);
}


$smarty->assign('viewstart', $viewstart);
$smarty->assign('viewend', $viewend);
$smarty->assign('numberofweeks', $numberofweeks);

$daysnames = array(
	tra("Sunday"),
	tra("Monday"),
	tra("Tuesday"),
	tra("Wednesday"),
	tra("Thursday"),
	tra("Friday"),
	tra("Saturday")
);

$weeks = array();
$cell = array();

if ($_SESSION['CalendarViewGroups']) {
	$listevents = $calendarlib->listItems($_SESSION['CalendarViewGroups'], $gBitUser->mUserId, $viewstart, $viewend, 0, 50, 'name_desc', '');
} else {
	$listevents = array();
}

if ($_SESSION['CalendarViewTikiCals']) {
	$listtikievents = $calendarlib->listTikiItems($_SESSION['CalendarViewTikiCals'], $gBitUser->mUserId, $viewstart, $viewend, 0, 50, 'name_desc', '');
} else {
	$listtikievents = array();
}

define("weekInSeconds", 604800);

// note that number of weeks starts at ZERO (i.e., zero = 1 week to display).
for ($i = 0; $i <= $numberofweeks; $i++) {
	$wee = $firstweek + $i;

	$weeks[] = $wee;

   // $startOfWeek is a unix timestamp
   $startOfWeek = $viewstart + $i * weekInSeconds;

	foreach ($weekdays as $w) {
		$leday = array();
	        $dday = $startOfWeek + $d * $w;
		$cell[$i][$w]['day'] = $dday;
		if (isset($listevents["$dday"])) {
			$e = 0;

			foreach ($listevents["$dday"] as $le) {
				$leday["{$le['time']}$e"] = $le;

				$smarty->assign_by_ref('cellextra', $le["extra"]);
				$smarty->assign_by_ref('cellhead', $le["head"]);
				$smarty->assign_by_ref('cellprio', $le["prio"]);
				$smarty->assign_by_ref('cellcalname', $le["calname"]);
				$smarty->assign_by_ref('cellname', $le["name"]);
				$smarty->assign_by_ref('celldescription', $le["description"]);
				$leday["{$le['time']}$e"]["over"] = $smarty->fetch("bitpackage:calendar/calendar_box.tpl");
				$e++;
			}
		}

		if (isset($listtikievents["$dday"])) {
			$e = 0;

			foreach ($listtikievents["$dday"] as $lte) {
				$leday["{$lte['time']}$e"] = $lte;

				$smarty->assign('cellextra', "");
				$smarty->assign_by_ref('cellhead', $lte["head"]);
				$smarty->assign_by_ref('cellprio', $lte["prio"]);
				$smarty->assign_by_ref('cellcalname', $lte["calname"]);
				$smarty->assign_by_ref('cellname', $lte["name"]);
				$smarty->assign_by_ref('celldescription', $lte["description"]);
				$leday["{$lte['time']}$e"]["over"] = $smarty->fetch("bitpackage:calendar/calendar_box.tpl");
				$e++;
			}
		}

		if (is_array($leday)) {
			ksort ($leday);
			$cell[$i][$w]['items'] = array_values($leday);
		}
	}
}

$hrows = array();
if ($_SESSION['CalendarViewMode'] == 'day') {
	foreach ($cell[0]["{$weekdays[0]}"]['items'] as $dayitems) {
		$rawhour = substr($dayitems['time'],0,2);
		$dayitems['mins'] = substr($dayitems['time'],2);
		$hrows["$rawhour"][] = $dayitems;
	}
}
$smarty->assign('hrows', $hrows); 

$smarty->assign('trunc', $trunc); 
$smarty->assign('daformat', $tikilib->get_long_date_format()." ".tra("at")." %H:%M"); 
$smarty->assign('daformat2', $tikilib->get_long_date_format()); 
$smarty->assign('currentweek', $currentweek);
$smarty->assign('firstweek', $firstweek);
$smarty->assign('lastweek', $lastweek);
$smarty->assign('weekdays', $weekdays);
$smarty->assign('weeks', $weeks);
$smarty->assign('daysnames', $daysnames);
$smarty->assign('cell', $cell);
$smarty->assign('var', '');

$section = 'calendar';


$gBitSystem->display( 'bitpackage:calendar/calendar.tpl');

//echo "<pre>";print_r($cell);echo "</pre>";
?>
